### ISSUE TITLE
No suitable devices.

### ISSUE THREAD

**Issue by adriankr2** [vbence/dvb-is#1]
Hi , i wanted to use my "August t202" Dvb-T device in java
and its throwing an IOException:

Exception in thread "main" java.io.IOException: No suitable devices.
    at org.czentral.dvb.io.LocalDeviceRegistry.openStreamAt(LocalDeviceRegistry.java:88)
    at org.czentral.dvb.io.StreamLocator.getInputStream(StreamLocator.java:61)
    at Dvb.Dvbt.main(Dvbt.java:14)

**Comment by vbence** [comment]
Hello, can you please include the full output of the test program? You can run it with something like:

```
java -jar dist/lib/dvb-is.jar org.czentral.dvb.io.NativeTest
```

What OS are you trying it on?

**Comment by adriankr2** [comment]
i am using Windows 7 prof.
this happends when i am trying to run the NaitveTest

Has native support: false
Numer of devices: 0
-- Tuning and reading a single packet two times
java.io.IOException: No suitable devices.
    at org.czentral.dvb.io.LocalDeviceRegistry.openStreamAt(LocalDeviceRegistry.java:88)
    at org.czentral.dvb.io.StreamLocator.getInputStream(StreamLocator.java:61)
    at org.czentral.dvb.io.NativeTest.main(NativeTest.java:64)

**Comment by vbence** [comment]
```
Has native support: false
```

... indicates that the DLL is not accessible. You have to compile the windows backend (windows directory). Unfortunately you will need Delphi 7 for that. I will try to upload a pre-compiled binary.

**Comment by adriankr2** [comment]
that would by nice thx

**Comment by adriankr2** [comment]
do you have the precompiled one?

**Comment by vbence** [comment]
Unfortunately neither do I have access to Delphi7 at the moment. I'm trying to find the distribution package from _Google Code_ - or get access to a D7. So stay tuned... it is coming. :)
